-- client_master
INSERT INTO
    `client_master` (
        `id` `clientNumber`,
        `companyName`,
        `honorific`,
        `firstName`,
        `middleInitial`,
        `lastName`,
        `address`,
        `city`,
        `state`,
        `zipCode`,
        `areaCode`,
        `phoneNumber`,
        `cOrP`,
        `dateForP`,
        `retailOrWholeSale`,
        `wType`,
        `taxId`,
        `totalSales`,
        `additionalInfo`,
        `lastInvoiceDate`,
        `fax`,
        `email`,
        `address2`,
        `isMailingList`
    )
SELECT
    `id` AS `id`,
    `Client Number` as `clientNumber`,
    `Company` as `companyName`,
    `Title` as `honorific`,
    `First Name` as `firstName`,
    `MI` as `middleInitial`,
    `Last Name` as `lastName`,
    `Addr 1` as `address`,
    `City` as `city`,
    `State` as `state`,
    `Zip` as `zipCode`,
    `AC` as `areaCode`,
    `Phone` as `phoneNumber`,
    `C or P` as `cOrP`,
    `Date for P` as `dateForP`,
    `Ret_whosale` as `retailOrWholeSale`,
    `W_Type` as `wType`,
    `Tax ID` as `taxId`,
    `Accum Total Sales` as `totalSales`,
    `Add'l Info` as `additionalInfo`,
    `Last Invoice Date` as `lastInvoiceDate`,
    `Fax` as `fax`,
    `Email` as `email`,
    `Addr 2` as `address2`,
    `Mailing List` as `isMailingList`
FROM
    `client`;